clean:
	./gradlew clean

build:
	./gradlew clean build

install:
	./gradlew install

start:
	./gradlew run

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

.PHONY: build